    IUM000  *** ERROR ***  …ˆ‡‚…‘’Ž… ‘ŽŽ™…ˆ…
    IUM001  *** ERROR ***  ŠŽ„ Ž…€–ˆˆ … Ž‡‚Ž‹Ÿ…’‘Ÿ ƒ……ˆŽ‚€’œ
    IUM002  *** ERROR ***  ‘ƒ……ˆŽ‚€›‰ Ž…€’Ž ‘‹ˆ˜ŠŽŒ „‹ˆ…. Ž…€’Ž “‘…Š€…’‘Ÿ
    IUM003  *** ERROR ***  …ŽšŸ‚‹…›‰ ‘ˆŒ‚Ž‹ ……Œ…Ž‰. ‡€—…ˆ… Ž “ŒŽ‹—€ˆž
    IUM004  *** ERROR ***  „“‹ˆ“ž™…… ŽšŸ‚‹…ˆ… set-……Œ…Ž‰. Ž‘’€…’‘Ÿ …‚Ž…
    IUM005  *** ERROR ***  …’ €ŒŸ’ˆ „‹Ÿ ‚“’……‰ Œ€ŠŽŠŽŒ€„›
    IUM007  *** ERROR ***  Œ…’Š€ ‘‹…„Ž‚€ˆŸ …„‚€ˆ’…‹œŽ Ž…„…‹…€
    IUM008  *** ERROR ***  ‘ˆŒ‚Ž‹ˆ—…‘Šˆ‰ €€Œ…’ …„‚€ˆ’…‹œŽ Ž…„…‹…
    IUM009  *** ERROR ***  ‘ˆ‘’…Œ›‰ ‘ˆŒ‚Ž‹ ……Œ…Ž‰ …€‚ˆ‹œŽ ……Ž…„…‹…
    IUM011  *** ERROR ***  …‘Ž‚Œ…‘’ˆŒ›… ƒ‹Ž€‹œ›… ŽšŸ‚‹…ˆŸ. ‘Ž•€Ÿ…’‘Ÿ …‚Ž…
    IUM012  *** ERROR ***  …Ž…„…‹…€Ÿ Œ…’Š€ ‘‹…„Ž‚€ˆŸ. Ž€Ž’Š€ Œ€ŠŽŽ…„…‹…ˆŸ …Š€™€…’‘Ÿ
    IUM013  *** ERROR ***  …‚›˜… ‘—…’—ˆŠ ACTR
    IUM017  *** ERROR ***  …Ž…„…‹…›‰ Š‹ž—…‚Ž‰ €€Œ…’
    IUM018  *** ERROR ***  „“‹ˆ“ž™…… Š‹ž—…‚Ž… ‘‹Ž‚Ž ‚ Œ€ŠŽŠŽŒ€„…. ˆ‘Ž‹œ‡“…’‘Ÿ Ž‘‹…„……
    IUM020  *** ERROR ***  …„…‰‘’‚ˆ’…‹œ›‰ Ž…€’Ž GBL ˆ‹ˆ LCL
    IUM021  *** ERROR ***  …„…‰‘’‚ˆ’…‹œ›‰ Ž…€’Ž SET
    IUM023  *** ERROR ***  ‘ˆŒ‚Ž‹ˆ—…‘Šˆ‰ €€Œ…’ ‘‹ˆ˜ŠŽŒ „‹ˆ›‰
    IUM024  *** ERROR ***  …„…‰‘’‚ˆ’…‹œ›‰ ‘ˆŒ‚Ž‹ ……Œ…Ž‰
    IUM025  *** ERROR ***  …„…‰‘’‚ˆ’…‹œ›‰ Ž…€„ Ž’Ž’ˆ€
    IUM026  *** ERROR ***  Ž…€„ Œ€ŠŽŠŽŒ€„› ‘‹ˆ˜ŠŽŒ „‹ˆ›‰
    IUM027  *** ERROR ***  —…‡Œ…Ž… ŠŽ‹ˆ—…‘’‚Ž Ž…€„Ž‚
    IUM028  *** ERROR ***  …„…‰‘’‚ˆ’…‹œŽ… ‘Œ…™…ˆ…
    IUM029  *** ERROR ***  …ŠŽ…Š’€Ÿ ‘…–ˆ”ˆŠ€–ˆŸ …ƒˆ‘’€ ˆ‹ˆ Œ€‘Šˆ
    IUM030  *** ERROR ***  …„…‰‘’‚ˆ’…‹œŽ… ˆ‘Ž‹œ‡Ž‚€ˆ… ‹ˆ’…€‹€
    IUM031  *** ERROR ***  …„…‰‘’‚ˆ’…‹œŽ… …Ž‘…„‘’‚…Ž… Ž‹…
    IUM032  *** ERROR ***  ……Œ…™€…ŒŽ… ‡€—…ˆ… €‰„…Ž ’€Œ, ƒ„… ’…“…’‘Ÿ €‘Ž‹ž’Ž… ‡€—…ˆ…
    IUM033  *** ERROR ***  Ž˜ˆŠ€ ‚›€‚ˆ‚€ˆŸ
    IUM034  *** ERROR ***  €„…‘“…ŒŽ‘’œ Ž˜ˆŽ—€
    IUM035  *** ERROR ***  …„…‰‘’‚ˆ’…‹œ›‰ €‡„…‹ˆ’…‹œ
    IUM036  *** ERROR ***  Ž˜ˆŠ€ ˆ Ž‚…Š… ……’…€…‹œŽ‘’ˆ
    IUM037  *** ERROR ***  …„…‰‘’‚ˆ’…‹œ›‰ ‘€ŒŽŽ…„…‹…›‰ ’…Œ
    IUM038  *** ERROR ***  ‡€—…ˆ… Ž…€„€ ‚›•Ž„ˆ’ ‡€ …„…‹› ’…Š“™…‰ ‘…Š–ˆˆ/‘—€Š
    IUM039  *** ERROR ***  Ž˜ˆŠ€ ‘—…’—ˆŠ€ €„…‘€
    IUM040  *** ERROR ***  Ž“™…›‰ Ž…€„
    IUM041  *** ERROR ***  Ž†ˆ„€‹‘Ÿ ’…Œ. ’…Š‘’ … Š‹€‘‘ˆ”ˆ–ˆ“…Œ›‰
    IUM042  *** ERROR ***  •€€Š’…ˆ‘’ˆŠ€ „‹ˆ› …Ž…„…‹…ŽƒŽ ˆŒ…ˆ. Ž “ŒŽ‹—€ˆž = 1
    IUM043  *** ERROR ***  …„‚€ˆ’…‹œŽ Ž…„…‹…Ž… ˆŒŸ
    IUM044  *** ERROR ***  …Ž…„…‹…Ž… ˆŒŸ
    IUM045  *** ERROR ***  …ƒˆ‘’ €…… … ˆ‘Ž‹œ‡Ž‚€‹‘Ÿ
    IUM046  *** ERROR ***  Ž…€„ €‰’€ ”‹€ƒ€ … Š€’… 8
    IUM047  *** ERROR ***  ŠŽ„ ‘…œ…‡Ž‘’ˆ Ž—…œ ‚…‹ˆŠ
    IUM048  *** ERROR ***  Ž˜ˆŽ—›‰ ENTRY
    IUM049  *** ERROR ***  …„…‰‘’‚ˆ’…‹œ›‰ „ˆ€€‡Ž ISEQ
    IUM050  *** ERROR ***  …„…‰‘’‚ˆ’…‹œŽ… Ž‹… €‡‚€ˆŸ. ˆŒŸ ˆƒŽˆ“…’‘Ÿ
    IUM051  *** ERROR ***  …„…‰‘’‚ˆ’…‹œ›‰ Ž…€’Ž ‚… Œ€ŠŽŽ…„…‹…ˆŸ
    IUM052  *** ERROR ***  Ž…€’Ž ‚… Ž‘‹…„Ž‚€’…‹œŽ‘’ˆ
    IUM053  *** ERROR ***  Ž…‹› ‚ Ž‹… Ž‘‹…„Ž‚€’…‹œŽ‘’ˆ
    IUM054  *** ERROR ***  …„…‰‘’‚ˆ’…‹œ€Ÿ ‘’ŽŠ€ Ž„Ž‹†…ˆŸ
    IUM055  *** ERROR ***  …Š“‘ˆ‚›‰ COPY
    IUM057  *** ERROR ***  …Ž…„…‹…›‰ ŠŽ„ Ž…€–ˆˆ
    IUM059  *** ERROR ***  …„…‰‘’‚ˆ’…‹œ›‰ ICTL
    IUM060  *** ERROR ***  ŠŽˆ“…Œ›‰ ŠŽ„ … €‰„…
    IUM061  *** ERROR ***  ˆŒŸ … Ÿ‚‹Ÿ…’‘Ÿ ˆŒ……Œ DSECT ˆ‹ˆ DXD
    IUM062  *** ERROR ***  …„…‰‘’‚ˆ’…‹œ›‰ ”ŽŒ€’ Ž…€„€
    IUM063  *** ERROR ***  …’ ŠŽ…—ŽƒŽ €Ž‘’Ž”€
    IUM064  *** ERROR ***  •€€Š’…ˆ‘’ˆŠ€ ‘ ‹€‚€ž™…‰ ’Ž—ŠŽ‰ ‚… …„…‹Ž‚
    IUM065  *** ERROR ***  …ˆ‡‚…‘’›‰ ’ˆ ŠŽ‘’€’›
    IUM066  *** ERROR ***  ……Œ…™€…Œ€Ÿ ŠŽ‘’€’€ ’ˆ€ Y
    IUM067  *** ERROR ***  …„…‰‘’‚ˆ’…‹œ›‰ ŠŽ””ˆ–ˆ…’ Š€’Ž‘’ˆ
    IUM068  *** ERROR ***  „‹ˆ€ Ž˜ˆŽ—€
    IUM070  *** ERROR ***  Ž˜ˆŽ—›‰ ŒŽ„ˆ”ˆŠ€’Ž Œ€‘˜’€€
    IUM071  *** ERROR ***  Ž˜ˆŽ—›‰ ŒŽ„ˆ”ˆŠ€’Ž ŽŸ„Š€
    IUM072  *** ERROR ***  ‹…Œ…’ „€›• ‘‹ˆ˜ŠŽŒ ‚…‹ˆŠ
    IUM073  *** ERROR ***  ’…Ÿ…’‘Ÿ ’Ž—Ž‘’œ
    IUM074  *** ERROR ***  …„…‰‘’‚ˆ’…‹œ›‰ ‘ˆ’€Š‘ˆ‘ ‚ ‚›€†…ˆˆ
    IUM075  *** ERROR ***  €ˆ”Œ…’ˆ—…‘ŠŽ… ……Ž‹…ˆ…
    IUM076  *** ERROR ***  …‚›˜…€ ‘‹Ž†Ž‘’œ Ž…€’Ž€
    IUM077  *** ERROR ***  –ˆŠ‹ˆ—…‘ŠŽ… Ž…„…‹…ˆ…
    IUM079  *** ERROR ***  …„…‰‘’‚ˆ’…‹œ›‰ PUSH-POP
    IUM080  *** ERROR ***  Ž…€’Ž … €‡…˜€…Œ›‰
    IUM081  *** ERROR ***  ‘Ž‡„€‚€…Œ€Ÿ SET-……Œ…€Ÿ …‚›˜€…’ 63 ‘ˆŒ‚Ž‹€
    IUM082  *** ERROR ***  ‘Ž‡„€‚€…Œ€Ÿ SET-……Œ…€Ÿ Ÿ‚‹Ÿ…’‘Ÿ “‹…‚Ž‰
    IUM083  *** ERROR ***  ‘Ž‡„€‚€…Œ€Ÿ SET-……Œ…€Ÿ … Ÿ‚‹Ÿ…’‘Ÿ €‚ˆ‹œ›Œ ˆŒ……Œ
    IUM084  *** ERROR ***  ‘ƒ……ˆŽ‚€Ž… Ž‹… €‡‚€ˆŸ …‚›˜€…’ 63 ‘ˆŒ‚Ž‹€. Ž’€‘›‚€…’‘Ÿ
    IUM085  *** ERROR ***  ƒ……ˆ“…ŒŽ… Ž‹… Ž…€„Ž‚ Ÿ‚‹Ÿ…’‘Ÿ “‹…‚›Œ
    IUM086  *** ERROR ***  Ž“™…›‰ MEND ƒ……ˆ“…’‘Ÿ
    IUM087  *** ERROR ***  ƒ……ˆ“…Œ›‰ ŠŽ„ Ž…€–ˆˆ “‹…‚Ž‰
    IUM088  *** ERROR ***  …‘€‹€‘ˆŽ‚€›… ‘ŠŽŠˆ ‚ Ž…€„… Œ€ŠŽŠŽŒ€„›
    IUM089  *** ERROR ***  €ˆ”Œ. ‚›€†…ˆ… ‘Ž„…†ˆ’ …„…‰‘’‚ˆ’…‹œ›‰ €‡„…‹ˆ’…‹œ ˆ‹ˆ …€‚ˆ‹œŽ ‡€Š€—ˆ‚€…’‘Ÿ
    IUM090  *** ERROR ***  ‹ˆ˜ŸŸ €‚€Ÿ ‘ŠŽŠ€ ‚ Ž…€„… Œ€ŠŽŠŽŒ€„›
    IUM091  *** ERROR ***  Ž…€„ SETC ˆ‹ˆ ‘ˆŒ‚Ž‹œŽƒŽ Ž’Ž˜…ˆŸ …‚›˜€…’ 255 ‘ˆŒ‚Ž‹Ž‚
    IUM092  *** ERROR ***  ‚›€†…ˆ… 1 Ž„‘’ŽŠˆ “Š€‡›‚€…’ Ž‘‹… ŠŽ–€ ‘’ŽŠˆ
    IUM093  *** ERROR ***  ‚›€†…ˆ… 1 Ž„‘’ŽŠˆ Œ…œ˜… —…Œ 1. Ž “ŒŽ‹—€ˆž = “‘’Ž…
    IUM094  *** ERROR ***  Ž„‘’ŽŠ€ Ž„Ž‹†€…’‘Ÿ Ž‘‹… ŠŽ–€ ‘’ŽŠˆ. Ž “ŒŽ‹—€ˆž = ˆŒ…ž™…‰‘Ÿ
    IUM095  *** ERROR ***  ‚›€†…ˆ… 2 Ž„‘’ŽŠˆ Œ…œ˜… 0. Ž “ŒŽ‹—€ˆž = “‘’Ž…
    IUM096  *** ERROR ***  …ˆ„…Š‘ˆŽ‚€›‰ SYSLIST. Ž “ŒŽ‹—€ˆž €‚… SYSLIST(1)
    IUM097  *** ERROR ***  …„…‰‘’‚ˆ’…‹œ€Ÿ ‘‘›‹Š€ € •€€Š’…ˆ‘’ˆŠ“ SETA- ˆ‹ˆ SETB-……Œ…Ž‰
    IUM098  *** ERROR ***  ‘‘›‹Š€ € •€€Š’…ˆ‘’ˆŠ“ …„…‰‘’‚ˆ’…‹œŽƒŽ ˆŒ…ˆ. Ž “ŒŽ‹—€ˆž = U ˆ‹ˆ 0
    IUM099  *** ERROR ***  …€‚ˆ‹œ›‰ ’ˆ ŠŽ‘’€’› „‹Ÿ ‘‘›‹Šˆ € •€€Š’…ˆ‘’ˆŠ“ S' ˆ‹ˆ I'. Ž “ŒŽ‹—.= 0
    IUM100  *** ERROR ***  ˆ„…Š‘ Œ…œ˜… —…Œ 1. Ž “ŒŽ‹—€ˆž ˆ„…Š‘ = 1
    IUM101  *** ERROR ***  ˆ„…Š‘ Œ…œ˜… —…Œ 1. Ž “ŒŽ‹—€ˆž ‡€—…ˆ… €‚Ž 0 ˆ‹ˆ “‘’Ž…
    IUM102  *** ERROR ***  €ˆ”Œ…’. ’…Œ … Ÿ‚‹Ÿ…’‘Ÿ ‘€ŒŽŽ…„…‹…›Œ ’…ŒŽŒ. Ž “ŒŽ‹—€ˆž = 0
    IUM103  *** ERROR ***  ……Ž‹…ˆ… “ŒŽ†…ˆŸ. Žˆ‡‚…„…ˆ… Ž “ŒŽ‹—€ˆž = 0
    IUM105  *** ERROR ***  €ˆ”Œ…’ˆ—…‘ŠŽ… ‚›€†…ˆ… ‘‹ˆ˜ŠŽŒ ‘‹Ž†Ž…
    IUM106  *** ERROR ***  …€‚ˆ‹œŽ… €‡€—…ˆ… ’ˆ€ ˆŒ…ˆ. ‡€—…ˆ… Ž‘’€…’‘Ÿ …ˆ‡Œ…›Œ
    IUM107  *** ERROR ***  …‘Ž‚Œ…‘’ˆŒ€Ÿ €‡Œ…Ž‘’œ ‘ €‡€—…ˆ…Œ ˆŒ…ˆ
    IUM108  *** ERROR ***  …‘Ž‚Œ…‘’ˆŒ€Ÿ €‡Œ…Ž‘’œ ‚ ‘‘›‹Š… € SET-……Œ…“ž
    IUM109  *** ERROR ***  …‘ŠŽ‹œŠŽ Ž…€„Ž‚ „‹Ÿ SET-……Œ…Ž‰ …‡ ˆ„…Š‘€
    IUM110  *** ERROR ***  …‚›‰ Ž…€’Ž ˆ‹ˆŽ’…—. Œ€ŠŽŽ…„…‹…ˆŸ - … MACRO, … ŠŽŒŒ…’€ˆ‰
    IUM111  *** ERROR ***  …„…‰‘’‚ˆ’…‹œŽ… Ž‹… Ž…€„Ž‚ AIF ˆ‹ˆ SETB
    IUM112  *** ERROR ***  …„…‰‘’‚ˆ’…‹œ€Ÿ Œ…’Š€ ‘‹…„Ž‚€ˆŸ
    IUM113  *** ERROR ***  ‚ Ž‡ˆ–ˆˆ Ž„Ž‹†…ˆŸ Ž…‹
    IUM114  *** ERROR ***  …„…‰‘’‚ˆ’…‹œ›‰ Ž…€„ COPY
    IUM115  *** ERROR ***  Ž…€„ COPY ‘‹ˆ˜ŠŽŒ „‹ˆ…
    IUM116  *** ERROR ***  …„…‰‘’‚ˆ’…‹œ€Ÿ SET-……Œ…€Ÿ
    IUM117  *** ERROR ***  …„…‰‘’‚ˆ’…‹œ›‰ ˆ„…Š‘
    IUM118  *** ERROR ***  ˆ‘•Ž„Ž… Œ€ŠŽŽ…„…‹…ˆ… ‡€ŠŽ—…Ž Ž…€’ŽŽŒ MEND ˆ‡ ŠŽˆ“…ŒŽƒŽ ŠŽ„€
    IUM119  *** ERROR ***  ‘‹ˆ˜ŠŽŒ Œ€‹Ž Ž…€’ŽŽ‚ MEND ‚ ŠŽˆ“…ŒŽŒ ŠŽ„…
    IUM120  *** ERROR ***  ŠŽ…– „€›• ’€Œ, ƒ„… Ž†ˆ„€‹Ž‘œ Ž„Ž‹†…ˆ… ‘’ŽŠˆ
    IUM121  *** ERROR ***  …„Ž‘’€’Ž—Ž €ŒŸ’ˆ „‹Ÿ €Ž—…‰ Ž‹€‘’ˆ …„€Š’Ž€
    IUM122  *** ERROR ***  …„…‰‘’‚ˆ’…‹œ›‰ ”ŽŒ€’ ŠŽ„€ Ž…€–ˆˆ
    IUM123  *** ERROR ***  ‘ˆŒ‚Ž‹ ……Œ…Ž‰ ‘‹ˆ˜ŠŽŒ „‹ˆ›‰
    IUM124  *** ERROR ***  …„…‰‘’‚ˆ’…‹œŽ… ˆ‘Ž‹œ‡Ž‚€ˆ… €€Œ…’€
    IUM125  *** ERROR ***  …„…‰‘’‚ˆ’…‹œŽ… ˆŒŸ Œ€ŠŽŽ…„…‹…ˆŸ - Œ€ŠŽŽ…„…‹…ˆ… …‚›‡›‚€…ŒŽ…
    IUM126  *** ERROR ***  ˆŒŸ ˆ‹ˆŽ’…—ŽƒŽ Œ€ŠŽŽ…„…‹…ˆŸ …€‚ˆ‹œŽ…
    IUM127  *** ERROR ***  …„…‰‘’‚ˆ’…‹œŽ… ˆ‘Ž‹œ‡Ž‚€ˆ… ‡€Š€ "&"
    IUM128  *** ERROR ***  ‹ˆ˜ŸŸ €‚€Ÿ ‘ŠŽŠ€
    IUM129  *** ERROR ***  … •‚€’€…’ €‚Ž‰ ‘ŠŽŠˆ
    IUM130  *** ERROR ***  …„…‰‘’‚ˆ’…‹œ€Ÿ ‘‘›‹Š€ € •€€Š’…ˆ‘’ˆŠ“
    IUM131  *** ERROR ***  ƒ‹“ˆ€ ‚‹Ž†…Ž‘’ˆ ‘ŠŽŽŠ …‚›˜€…’ 255
    IUM132  *** ERROR ***  …„…‰‘’‚ˆ’…‹œŽ… ‚›€†…ˆ… SETB
    IUM133  *** ERROR ***  …„…‰‘’‚ˆ’…‹œ€Ÿ ‘‘›‹Š€ € Ž„‘’ŽŠ“
    IUM134  *** ERROR ***  …„…‰‘’‚ˆ’…‹œ€Ÿ Ž…€–ˆŸ Ž’Ž˜…ˆŸ
    IUM135  *** ERROR ***  …„…‰‘’‚ˆ’…‹œ€Ÿ ‹Žƒˆ—…‘Š€Ÿ Ž…€–ˆŸ
    IUM136  *** ERROR ***  …„…‰‘’‚ˆ’…‹œ€Ÿ ‹Žƒˆ—…‘Š€Ÿ Ž…€–ˆŸ ˆ‹ˆ Ž…€–ˆŸ Ž’Ž˜…ˆŸ
    IUM137  *** ERROR ***  …„…‰‘’‚ˆ’…‹œŽ… ‚›€†…ˆ… SETC
    IUM139  *** ERROR ***  ŠŽ…– „€›• ‚Ž ‚…ŒŸ Ž€Ž’Šˆ REPRO
    IUM140  *** ERROR ***  Ž“™… Ž…€’Ž  END
    IUM141  *** ERROR ***  ‹Ž•Ž‰ ‘ˆŒ‚Ž‹ ‚ ŠŽ„… Ž…€–ˆˆ
    IUM142  *** ERROR ***  ŠŽ„ Ž…€–ˆˆ … ‡€‚…˜€…’‘Ÿ ‚ …‚Ž‰ ‘’ŽŠ…
    IUM143  *** ERROR ***  ‹Ž•Ž‰ ‘ˆŒ‚Ž‹ ‚ Ž‹… €‡‚€ˆŸ
    IUM144  *** ERROR ***  ‚ Ž‡ˆ–ˆŸ• Ž’ €—€‹€ „Ž Ž„Ž‹†…ˆŸ … Ž…‹›
    IUM145  *** ERROR ***  Ž†ˆ„€‹€‘œ Ž…€–ˆŸ, €‚€Ÿ ‘ŠŽŠ€ ˆ‹ˆ ŠŽ…– ‚›€†…ˆŸ
    IUM146  *** ERROR ***  ‘€ŒŽŽ…„…‹…›‰ ’…Œ ‘‹ˆ˜ŠŽŒ „‹ˆ›‰ ˆ‹ˆ ‡€—…ˆ… ‘‹ˆ˜ŠŽŒ ‚…‹ˆŠŽ
    IUM147  *** ERROR ***  ˆŒŸ ‘‹ˆ˜ŠŽŒ „‹ˆŽ… ˆ‹ˆ …‚›‰ ‘ˆŒ‚Ž‹ … “Š‚€
    IUM148  *** ERROR ***  ‚ ‘€ŒŽŽ…„…‹…ŽŒ ’…Œ… … •‚€’€…’ ŠŽ…—ŽƒŽ €Ž‘’Ž”€ ˆ‹ˆ …‘’œ ‹Ž•Ž‰ ‘ˆŒ‚Ž‹
    IUM149  *** ERROR ***  „‹ˆ€ ‹ˆ’…€‹€ …‚›˜€…’ 256 ‘ˆŒ‚Ž‹Ž‚, ‚Š‹ž—€Ÿ ‡€Š €‚…‘’‚€
    IUM150  *** ERROR ***  ˆŒŸ ˆŒ……’ … €‹”€‚ˆ’Ž-–ˆ”Ž‚Ž‰ ‘ˆŒ‚Ž‹ ˆ‹ˆ …„…‰‘’‚ˆ’…‹œ›‰ €‡„…‹ˆ’…‹œ
    IUM151  *** ERROR ***  ŒŽ„ˆ”ˆŠ€’Ž› ‚ ‹ˆ’…€‹… „Ž‹†› ›’œ €‘Ž‹ž’›Œˆ ˆ …„‚€ˆ’…‹œŽ Ž…„…‹…›
    IUM152  *** ERROR ***  ‚…˜…… ˆŒŸ ‘‹ˆ˜ŠŽŒ „‹ˆŽ… ˆ‹ˆ … ‚Ž‘ˆˆŒ€…Œ›‰ ‘ˆŒ‚Ž‹
    IUM153  *** ERROR ***  …„…‰‘’‚ˆ’…‹œ›‰ Ž…€’Ž START - “†… €—€’€ ‘…Š–ˆŸ
    IUM154  *** ERROR ***  Ž…€„ „Ž‹†… ›’œ €‘Ž‹ž’›Œ, ˆŒ…€ …„‚€ˆ’…‹œŽ Ž…„…‹…›
    IUM155  *** ERROR ***  …„›„“™…… ˆ‘Ž‹œ‡Ž‚€ˆ… ˆŒ…ˆ … Ÿ‚‹Ÿ…’‘Ÿ ’ˆŽŒ ’Ž‰ ‘…Š–ˆˆ
    IUM156  *** ERROR ***  „Ž“‘Š€ž’‘Ÿ ’Ž‹œŠŽ Ž›—›… ˆŒ…€, €‡„…‹…›… ‡€Ÿ’›Œˆ
    IUM157  *** ERROR ***  Ž…€„ „Ž‹†… ›’œ Ž‘’›Œ ……Œ…™€…Œ›Œ ‚›€†…ˆ…Œ
    IUM158  *** ERROR ***  …‚›‰ Ž…€„ ‚›€†…ˆŸ …€‚ˆ‹œ›‰. “‘’€€‚‹ˆ‚€…’‘Ÿ ‚ *
    IUM159  *** ERROR ***  Ž…€„› „Ž‹†› ›’œ €‘Ž‹ž’›Œˆ, „Ž‹†› ›’œ Š€’› 2 ˆ‹ˆ 4
    IUM161  *** ERROR ***  ’Ž‹œŠŽ Ž„ˆ TITLE ŒŽ†…’ ˆŒ…’œ €‡‚€ˆ…
    IUM162  *** ERROR ***  Ž…€„ PUNCH …‚›˜€…’ 80 Ž‡ˆ–ˆ‰. ˆƒŽˆ“…’‘Ÿ
    IUM163  *** ERROR ***  Ž…€„ … ‡€Š‹ž—… ‚ €Ž‘’Ž”›, Š€Š “†Ž
    IUM164  *** ERROR ***  Ž…€„ Ÿ‚‹Ÿ…’‘Ÿ “‘’Ž‰ ‘’ŽŠŽ‰ 
    IUM165  *** ERROR ***  …Ž†ˆ„€…ŒŽ… Ž‹… €‡‚€ˆŸ
    IUM166  *** ERROR ***  Œ…’Š€ ‘‹…„Ž‚€ˆŸ ‘‹ˆ˜ŠŽŒ „‹ˆ€Ÿ
    IUM167  *** ERROR ***  ’…“…ŒŽ… ˆŒŸ Ž“™…Ž
    IUM168  *** ERROR ***  …Ž…„…‹…€Ÿ Œ…’Š€ ‘‹…„Ž‚€ˆŸ
    IUM169  *** ERROR ***  ‚‘… ˆŒ…€ ‚ ‚›€†…ˆˆ „Ž‹†› ›’œ ‹ˆŽ €‘Ž‹ž’›Œˆ, ‹ˆŽ Ž‘’›Œˆ ……Œ…™€…Œ›Œˆ
    IUM170  *** ERROR ***  …‚›˜…€ …ŒŠŽ‘’œ …ƒˆ‘’€–ˆˆ Ž˜ˆŽŠ ŽŒ…†“’Ž—Ž‰ Ž€Ž’Šˆ
    IUM171  *** ERROR ***  ‘’€„€’Ž… ‡€—…ˆ… ‘‹ˆ˜ŠŽŒ „‹ˆŽ…
    IUM172  *** ERROR ***  Ž’ˆ–€’…‹œ›‰ ŠŽ””ˆ–ˆ…’ Š€’Ž‘’ˆ. Ž “ŒŽ‹—€ˆž = 1
    IUM173  *** ERROR ***  Ž˜ˆŽ—›‰ €‡„…‹ˆ’…‹œ, Ž†ˆ„€‹‘Ÿ Ž…‹
    IUM174  *** ERROR ***  Ž˜ˆŽ—›‰ €‡„…‹ˆ’…‹œ, Ž†ˆ„€‹‘Ÿ Ž…‹ ˆ‹ˆ ‡€Ÿ’€Ÿ
    IUM175  *** ERROR ***  Ž˜ˆŽ—›‰ €‡„…‹ˆ’…‹œ, Ž†ˆ„€‹€‘œ ‡€Ÿ’€Ÿ
    IUM176  *** ERROR ***  Ž˜ˆŽ—›‰ €‡„…‹ˆ’…‹œ, Ž†ˆ„€‹€‘œ ‡€Ÿ’€Ÿ ˆ‹ˆ ‹…‚€Ÿ ‘ŠŽŠ€
    IUM177  *** ERROR ***  Ž˜ˆŽ—›‰ €‡„…‹ˆ’…‹œ, Ž†ˆ„€‹‘Ÿ Ž…‹ ˆ‹ˆ ‹…‚€Ÿ ‘ŠŽŠ€
    IUM178  *** ERROR ***  Ž˜ˆŽ—›‰ €‡„…‹ˆ’…‹œ, Ž†ˆ„€‹€‘œ ‡€Ÿ’€Ÿ ˆ‹ˆ €‚€Ÿ ‘ŠŽŠ€
    IUM179  *** ERROR ***  Ž˜ˆŽ—›‰ €‡„…‹ˆ’…‹œ, Ž†ˆ„€‹€‘œ €‚€Ÿ ‘ŠŽŠ€
    IUM180  *** ERROR ***  Ž…€„ „Ž‹†… ›’œ €‘Ž‹ž’›Œ
    IUM181  *** ERROR ***  ‡€—…ˆ… Ž…€„€ CCW ‚… „Ž“‘’ˆŒŽƒŽ …„…‹€
    IUM182  *** ERROR ***  Ž…€„ 2 „Ž‹†… ›’œ €‘Ž‹ž’›Œ, 0-65535, ˆƒŽˆ“…’‘Ÿ
    IUM183  *** ERROR ***  Ž…€„ 3 „Ž‹†… ›’œ €‘Ž‹ž’›Œ, 0-255, ˆƒŽˆ“…’‘Ÿ
    IUM184  *** ERROR ***  ‘Ž‰ ŠŽˆŽ‚€ˆŸ
    IUM185  *** ERROR ***  Ž…€„ 2 Ž˜ˆŽ—…
    IUM186  *** ERROR ***  Žƒ€ŒŒ€ ‘‹ˆ˜ŠŽŒ „‹ˆ€Ÿ
    IUM253  *** ERROR ***  ‘‹ˆ˜ŠŽŒ ŒŽƒŽ Ž˜ˆŽŠ
    IUM254  *** ERROR ***  *** MNOTE ***
    IUM300  *** ERROR ***  …„Ž‘’€’Ž—›‰ Žš…Œ €ŒŸ’ˆ ˆ Ž€Ž’Š… PUSH-POP
    IUM301  *** ERROR ***  “Ž‚…œ ‚‹Ž†…Ž‘’ˆ PUSH-POP > 4
    IUM400  *** ERROR ***  …„Ž‘’€’Ž—›‰ Žš…Œ €ŒŸ’ˆ ˆ ‚›—ˆ‘‹…ˆˆ ‚›€†…ˆŸ
    IUM401  *** ERROR ***  …„Ž“‘’ˆŒŽ… —ˆ‘‹Ž ‘€ŒŽŽ…„…‹…›• ’…ŒŽ‚ ‚ ‚›€†…ˆˆ
    IUM500  *** ERROR ***  ‚ ‡€ˆ‘ˆ Ž€“†…€ Ž˜ˆŠ€ ”ŽŒ€’€
    IUM501  *** ERROR ***  ˆŒŸ ”€‰‹€ Ž’‹ˆ—Ž Ž’ Œ…’Šˆ Ž…€’Ž€  UGBEGIN (ˆ‹ˆ START)
    IUM502  *** ERROR ***  …‘ŽŽ’‚…’‘’‚ˆ… ’ˆ€ ‹ŽŠ€ (‚	UGBEGIN) ’ˆ“ ‡€Ž‘€
    IUM503  *** ERROR ***  Ž˜ˆŠ€ ‚ ˆ‘Ž‹œ‡Ž‚€ˆˆ Ž…€’Ž€  ‘ “ƒ€
    IUM504  *** ERROR ***  ‚ Ž€€’›‚€…ŒŽŒ ‹ŽŠ… …’ ‘ŽŽ’‚…’‘’‚ˆŸ Œ…†„“  UGBEGIN  ˆ  UGEND
    IUM505  *** ERROR ***  …€‚ˆ‹œŽ ‡€„€Ž ˆŒŸ ‹ŽŠ€
    IUM506  *** ERROR ***  …†„…‚…Œ…Ž… ˆ‘Ž‹œ‡Ž‚€ˆ… Ž…€’Ž€  UGSTRUCT
    IUM507  *** ERROR ***  ‚ Ž‹… Ž…€„Ž‚ Ž…€’Ž€  UGSTRUCT  … ‡€„€Ž ˆŒŸ ……Œ…Ž‰
    IUM508  *** ERROR ***  Ž˜ˆŠ€ ‚ ‡€„€ˆˆ ˆŒ…ˆ ……Œ…Ž‰ ‚ Ž‹… Ž…€„Ž‚ Ž…€’Ž€  UGSTRUCT
    IUM509  *** ERROR ***  Ž˜ˆŠ€ ‚ ‡€„€ˆˆ Ž…€’Ž›• ‘ŠŽŽŠ	‘ “ƒ€
    IUM510  *** ERROR ***  Ž˜ˆŠ€ ‚ ‡€„€ˆˆ ‘“””ˆŠ‘€ ‚ Ž‹… Ž…€„Ž‚ Ž…€’Ž€  UGSTRUCT
    IUM511  *** ERROR ***  Ž˜ˆŠ€ ˆ €‡‚…’›‚€ˆˆ ‹ˆŽ „ŽŽ‹ˆ’…‹œŽƒŽ ‹ŽŠ€ ‹ˆŽ €Š‹€„›‚€…ŒŽ‰ ‘’“Š’“›
    IUM512  *** ERROR ***  …’ ‘ŽŽ’‚…’‘’‚ˆŸ Œ…†„“ —ˆ‘‹ŽŒ ‡€€˜ˆ‚€…Œ›• ˆ —ˆ‘‹ŽŒ ‘—ˆ’€›• „Ž. ‹ŽŠŽ‚
    IUM513  *** ERROR ***  „ŽŽ‹ˆ’…‹œ›‰ ‹ŽŠ …„‚€ˆ’…‹œŽ … Ž’’€‘‹ˆŽ‚€
    IUM514  *** ERROR ***  Ž…€’Ž  UGEND  „Ž‹†… ›’œ €‘Ž‹Ž†… € Ž„Ž‰ ‘’ŽŠ…
    IUM515  *** ERROR ***  Ž…€’Ž  UGEND  €‘Ž‹Ž†… … ‚ Ž‘‹…„…‰ ‘’ŽŠ… Ž€€’›‚€…ŒŽƒŽ ‹ŽŠ€
    IUM516  *** ERROR ***  Ž€“†…€ Ž˜ˆŠ€ ‚ ‘’“Š’“… Ž…€’Ž€  UGEND
    IUM517  *** ERROR ***  …€‚ˆ‹œ€Ÿ ŠŽ’Ž‹œ€Ÿ ‘“ŒŒ€ ˆ”ŽŒ€–ˆˆ ‹ŽŠ€
    IUM518  *** ERROR ***  …’ ‘ˆŒ‚Ž‹€ ŠŽ–€ ‚ Ž‘‹…„…‰ ‘’ŽŠ… ”€‰‹€ „ŽŽ‹ˆ’…‹œŽƒŽ ‹ŽŠ€
    IUM519  *** ERROR ***  ……Ž‹…ˆ… …‘“‘Ž‚ ‚“’…ˆ• ’€‹ˆ– ’€‘‹Ÿ’Ž€ (3072) 
    IUM520  *** ERROR ***  Ž’‘“’‘’‚“…’ Ž…€’Ž €—€‹€ Žƒ€ŒŒ› (START ¨«¨ UGBEGIN )
    IUM521  *** ERROR ***  …ˆŒ…Ž‚€€Ÿ ‘…Š–ˆŸ ‚ „ŽŽ‹ˆ’…‹œŽŒ ‹ŽŠ… … „Ž“‘Š€…’‘Ÿ
    IUM522  *** ERROR ***  ‚ ’…Š‘’… …„Ž“‘’ˆŒ›‰ ‘ˆŒ‚Ž‹ (… ‘ŽŽ’‚…’‘’‚“…’ ŠŽ„ˆŽ‚Š…  MS-DOS)
    IUM523  *** ERROR ***  ‚ ’…Š‘’… …„Ž“‘’ˆŒ›‰ ‘ˆŒ‚Ž‹ (… ‘ŽŽ’‚…’‘’‚“…’ ŠŽ„ˆŽ‚Š…  WINDOWS)
    IUM524  *** ERROR ***  Ž˜ˆŠ€ ‚ €‹ƒŽˆ’Œ… €‘…„…‹…ˆŸ €ŒŸ’ˆ ‚ ’€‘‹Ÿ’Ž…
    IUM525  *** ERROR ***  „ŽŽ‹ˆ’…‹œ›‰ ‹ŽŠ … ‚ ‹ŽŠ… ŠŽŒ€„ (… ‚ ‹ŽŠ… ’ˆ€ Q)
    IUM526  *** ERROR ***  „‹ˆ€ ˆ”ŽŒ€–ˆˆ Ž…€’Ž€ TITLE Ž‹œ˜… „Ž“‘’ˆŒŽ‰
    IUM527  *** ERROR ***  „‹ˆ€ ‘’ŽŠˆ ’…Š‘’€ „ŽŽ‹ˆ’…‹œŽƒŽ ‹ŽŠ€ Ž‹…… 80-’ˆ ‘ˆŒ‚Ž‹Ž‚
    IUM528  *** ERROR ***  … €‰„… ‹ŽŠ, €Š‹€„›‚€…Œ›‰ Ž Ž…€’Ž“ UGSTRUCT
    IUM529  *** ERROR ***  „‹ˆ€ ‘’ŽŠˆ ’…Š‘’€ Ž‹…… 80 -’ˆ ‘ˆŒ‚Ž‹Ž‚
    IUM530  *** ERROR ***  ……Ž‹…ˆ… ’€‹ˆ–› Œ…’ŽŠ ‘‹…„Ž‚€ˆŸ
    IUM531  *** ERROR ***  Ž’‘“’‘’‚“…’ Ž…€’Ž  UGEND  ‚ „ŽŽ‹ˆ’…‹œŽŒ ‹ŽŠ…
    IUM532  *** ERROR ***  Ž‚’ŽŽ… ‡€„€ˆ… Ž…€’Ž€  UGBEGIN  ‚ ”€‰‹…
    IUM533  *** ERROR ***  Ž’‘“’‘’‚“…’ …Ž•Ž„ˆŒ›‰ Ž…€’Ž  UGBCOPY  
    IUM534  *** ERROR ***  Ž˜ˆŠ€ ‚ ‡€„€ˆˆ Ž…€„€ Ž…€’Ž€  UGBCOPY
    IUM535  *** ERROR ***  Ž˜ˆŠ€ ‚ ‘’ŽŠ… Ž„Ž‹†…ˆŸ Ž…€’Ž€  UGBCOPY
    IUM536  *** ERROR ***  ‡€„€ˆ… Ž…€’ŽŽ‚  UGBCOPY  ‘ Ž„ˆ€ŠŽ‚›Œˆ ŽŒ…€Œˆ 
    IUM537  *** ERROR ***  Ž‚’ŽŽ… ‡€„€ˆ… Ž…€’Ž€  UGBCOPY  …‡ ŽŒ…€
    IUM538  *** ERROR ***  Ž…€’Ž“ UGECOPY …’ ‘ŽŽ’‚…’‘’‚“ž™…ƒŽ Ž…€’Ž€ UGBCOPY
    IUM539  *** ERROR ***  Ž’‘“’‘’‚“…’ Ž…€’Ž  UGBEGIN  ‚ Ž‘Ž‚ŽŒ ‹ŽŠ… 
    IUM540  *** ERROR ***  ƒ……€–ˆŸ Ž‹Ÿ ‚ Ž…€’Ž… UGBEGIN ˆ‹ˆ UGBCOPY ˆ‹ˆ UGECOPY
    IUM541  *** ERROR ***  Ž…€’Ž  UGBCOPY ˆ‹ˆ UGECOPY  ‚ Œ€ŠŽ€‘˜ˆ…ˆˆ Œ€ŠŽŠŽŒ€„›  
    IUM542  *** ERROR ***  ‡€…™…€Ÿ Ž‘‹…„Ž‚€’…‹œŽ‘’œ ŠŽŒ€„
    IUM543  *** ERROR ***  Ž˜ˆŠ€ ˆ ”ŽŒˆŽ‚€ˆˆ ‘‹Ž‚€…‰ ESD / RLD
    IUM544  *** ERROR ***  Ž˜ˆŠ€ ‚ ‡€„€ˆˆ ‹ˆ’…€‹€
    IUM545  *** ERROR ***  … „Ž“‘Š€…’‘Ÿ ‹ˆ’…€‹ ‘ ‚…˜…‰ ‘‘›‹ŠŽ‰ ‚ ”ˆŠ’ˆ‚Ž‰ ‘…Š–ˆˆ 
    IUM546  *** ERROR ***  … Ž€€’›‚€ž’‘Ÿ Ž…€’Ž› EXTRN ‚ ”ˆŠ’ˆ‚›• ‘…Š–ˆŸ•
    IUM547  *** ERROR ***  ……Ž‹…ˆ… €Ž—ˆ• Œ€‘‘ˆ‚Ž‚ ’€‘‹Ÿ’Ž€. …Ž•Ž„ˆŒŽ €‘˜ˆ…ˆ… …‘“‘Ž‚
    IUM548  *** ERROR ***  …‘ŽŽ’‚…’‘’‚ˆ… …„‹Ž†…ˆŸ ’ˆ“ ‹ŽŠ€, ‡€„€ŽŒ“ ‚ UGBEGIN
    IUM549  *** ERROR ***  Ž˜ˆŠ€ ˆ ”ŽŒˆŽ‚€ˆˆ ‡€ˆ‘ˆ ESD
    IUM550  *** ERROR ***  Ž˜ˆŠ€ ˆ ”ŽŒˆŽ‚€ˆˆ ‡€ˆ‘ˆ SYM
    IUM551  *** ERROR ***  Ž‚’ŽŽ “Š€‡€ Ž„ˆ ˆ ’Ž’ †… „ŽŽ‹ˆ’…‹œ›‰ ‹ŽŠ
    IUM552  *** ERROR *** 
    IUM553  *** ERROR *** 
    IUM554  *** ERROR *** 
    IUM555  *** ERROR *** 
    IUM620  *** ERROR ***  …„‚€ˆ’…‹œŽ Ž…„…‹…Ž… ˆŒŸ ‹ŽŠ€
    IUM621  *** ERROR ***  ‘‹ˆ˜ŠŽŒ ŒŽƒŽ „ŽŽ‹ˆ’…‹œ›• ‹ŽŠŽ‚
    IUM622  *** ERROR ***  ‘‹ˆ˜ŠŽŒ ŒŽƒŽ ‘’“Š’“
    IUM623  *** ERROR ***  Ž˜ˆŠ€ ‚ ‡€„€ˆˆ Œ…’Šˆ ‚ ‹ŽŠ…
    IUM624  *** ERROR ***  Ž˜ˆŠ€ ‚ ‡€„€ˆˆ Ž…€’Ž›• ‘ŠŽŽŠ ‚ ‹ŽŠ…
    IUM625  *** ERROR ***  Ž˜ˆŠ€ ‚ ‡€„€ˆˆ ‘“””ˆŠ‘€
    IUM626  *** ERROR ***  …ŠŽ…Š’Ž… ˆ‘Ž‹œ‡Ž‚€ˆ… Ž…€’Ž€ UGSTRUCT
    IUM627  *** ERROR ***  „ŽŽ‹ˆ’…‹œ›‰ ‹ŽŠ … €‰„…
    IUM628  *** ERROR ***  ‹ŽŠ, ‘Ž„…†€™ˆ‰ €Š‹€„›‚€…Œ“ž ‘’“Š’““, … €‰„…
    IUM629  *** ERROR ***  …Ž…„…‹…›‰ ŠŽ„ Ž…€–ˆˆ ‚ ’…Š‘’… Œ€ŠŽŠŽŒ€„›
    IUM700  *** ERROR ***  €ŒŸ’œ „‹Ÿ ’€‹ˆ–› ‡€—…ˆ‰ ‚›„…‹ˆ’œ … “„€‹Ž‘œ
    IUM701  *** ERROR ***  ……Ž‹…€ ’€‹ˆ–€ ‡€—…ˆ‰
    IUM702  *** ERROR ***  €ŒŸ’œ „‹Ÿ ’€‹ˆ–› SET-……Œ…›• ‚›„…‹ˆ’œ … “„€‹Ž‘œ
    IUM703  *** ERROR ***  ……Ž‹…€ ’€‹ˆ–€ SET-……Œ…›•
    IUM704  *** ERROR ***  €ŒŸ’œ „‹Ÿ ’€‹ˆ–› ƒ‹Ž€‹œ›• SET-……Œ…›• ‚›„…‹ˆ’œ … “„€‹Ž‘œ
    IUM705  *** ERROR ***  ……Ž‹…€ ’€‹ˆ–€ ƒ‹Ž€‹œ›• SET-……Œ…›•
    IUM706  *** ERROR ***  €ŒŸ’œ „‹Ÿ ’€‹ˆ–› Œ€ŠŽŽ…„…‹…ˆ‰ ‚›„…‹ˆ’œ … “„€‹Ž‘œ
    IUM707  *** ERROR ***  ……Ž‹…€ ’€‹ˆ–€ Œ€ŠŽŽ…„…‹…ˆ‰
    IUM708  *** ERROR ***  €ŒŸ’œ „‹Ÿ ’€‹ˆ–› SET-……Œ…›• Œ€ŠŽŽ…„…‹…ˆŸ ‚›„…‹ˆ’œ … “„€‹Ž‘œ
    IUM709  *** ERROR ***  ……Ž‹…€ ’€‹ˆ–€ SET-……Œ…›• Œ€ŠŽŽ…„…‹…ˆŸ
    IUM710  *** ERROR ***  €ŒŸ’œ „‹Ÿ ’€‹ˆ–› Œ…’ŽŠ ‘‹…„Ž‚€ˆŸ Œ€ŠŽŽ…„…‹…ˆ‰ ‚›„…‹ˆ’œ … “„€‹Ž‘œ
    IUM711  *** ERROR ***  ……Ž‹…€ ’€‹ˆ–€ Œ…’ŽŠ ‘‹…„Ž‚€ˆŸ Œ€ŠŽŽ…„…‹…ˆ‰
    IUM712  *** ERROR ***  €ŒŸ’œ „‹Ÿ ’€‹ˆ–› ‚‹Ž†…›• Ž…€’ŽŽ‚ COPY ‚ Œ€ŠŽŽ…„…‹…ˆˆ ‚›„…‹ˆ’œ … “„€‹Ž‘œ
    IUM713  *** ERROR ***  ……Ž‹…€ ’€‹ˆ–€ ‚‹Ž†…›• Ž…€’ŽŽ‚ COPY ‚ Œ€ŠŽŽ…„…‹…ˆˆ
    IUM714  *** ERROR ***  €ŒŸ’œ „‹Ÿ ’€‹ˆ–› Œ€ŠŽŠŽŒ€„ ‚›„…‹ˆ’œ … “„€‹Ž‘œ
    IUM715  *** ERROR ***  ……Ž‹…€ ’€‹ˆ–€ Œ€ŠŽŠŽŒ€„
    IUM716  *** ERROR ***  €ŒŸ’œ Ž„ ’€‹ˆ–“ Œ…’ŽŠ ‘‹…„Ž‚€ˆŸ ‚›„…‹ˆ’œ … “„€‹Ž‘œ
    IUM717  *** ERROR ***  ’€‹ˆ–› Œ…’ŽŠ ‘‹…„Ž‚€ˆŸ ……Ž‹…›
    IUM718  *** ERROR ***  €ŒŸ’œ Ž„ ’€‹ˆ–“ ˆŒ… ‚›„…‹ˆ’œ … “„€‹Ž‘œ
    IUM719  *** ERROR ***  ’€‹ˆ–› ˆŒ… ……Ž‹…›
    IUM720  *** ERROR ***  
    IUM972  *** ERROR ***  …„Ž‘’€’Ž—Ž €ŒŸ’ˆ - €‘…„…‹ˆ’œ Ž‹œ˜… €ŒŸ’ˆ ˆ‹ˆ €‡ˆ’œ € …‘ŠŽ‹œŠŽ ’€‘‹Ÿ–ˆ‰

